NReco.Recommender/src/NReco.Recommender.Examples.MovieLensMvc/Controllers/RecommenderController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.IO;
using System.Net;
using System.Threading;
using System.Web.Script.Serialization;

using System.Web.Security;

using NReco.CF.Taste.Model;
using NReco.CF.Taste.Impl.Model.File;
using NReco.CF.Taste.Impl.Eval;
using NReco.CF.Taste.Eval;
using NReco.CF.Taste.Impl.Similarity;
using NReco.CF.Taste.Impl.Neighborhood;
using NReco.CF.Taste.Impl.Recommender;
using NReco.CF.Taste.Impl.Recommender.SVD;
using NReco.CF.Taste.Impl.Model;
using NReco.CF.Taste.Recommender;

namespace Controllers {
	
	public class RecommenderController : Controller {

		public ActionResult RecommendFilmPage() {
			return View();
		}

		static IDataModel dataModel;

		public ActionResult Recommend(string filmIdsJson) {
			var filmIds = (new JavaScriptSerializer()).Deserialize<long[]>(filmIdsJson);
			var pathToDataFile =
					Path.Combine(System.Web.HttpRuntime.AppDomainAppPath, "data/albums.dat");

			if (dataModel == null) {
                try
                {
                    dataModel = new FileDataModel(pathToDataFile, false, FileDataModel.DEFAULT_MIN_RELOAD_INTERVAL_MS, false);
                }
                catch (Exception e)
                {
                    var exe = e.ToString();
                }
			}

			var plusAnonymModel = new PlusAnonymousUserDataModel(dataModel);
			var prefArr = new GenericUserPreferenceArray(filmIds.Length);
			prefArr.SetUserID(0, PlusAnonymousUserDataModel.TEMP_USER_ID);
			for (int i = 0; i < filmIds.Length; i++) {
				prefArr.SetItemID(i, filmIds[i]);
				prefArr.SetValue(i, 5); // lets assume max rating
			}
			plusAnonymModel.SetTempPrefs(prefArr);

			var similarity = new LogLikelihoodSimilarity(plusAnonymModel);
			var neighborhood = new NearestNUserNeighborhood(15, similarity, plusAnonymModel);
			var recommender = new GenericBooleanPrefUserBasedRecommender(plusAnonymModel, neighborhood, similarity);
			var recommendedItems = recommender.Recommend(PlusAnonymousUserDataModel.TEMP_USER_ID, 5, null);
			return Json( recommendedItems.Select(ri => new Dictionary<string, object>() {
				{"id", ri.GetItemID() },
				{"rating", ri.GetValue() },
			}).ToArray() );
		}



	}
}

NReco.Recommender/src/NReco.Recommender.Examples.MovieLensMvc/Views/Recommender/RecommendFilmPage.cshtml
@model System.Collections.IDictionary
	
	<div class="row-fluid">
		<div class="span12">
			<div class="pull-left">
				<h1>
					<a href="http://www.certifiedmixtapez.com">Certified Mixtapes</a> Recommender for .NET
					<small>Based on Mahout Taste port</small>
				</h1>
			</div>
			<div class="clearfix"></div>
		</div>
    </div>
	<hr />
	
	<div class="row-fluid">
		<div class="span12">
			
			<h2>Get Mixtape recommendations</h2>

			Select your favorite mixtapes:<br />
			<table class="table table-bordered selectedfilms" style="margin-bottom:10px;">
				<tr class="film" data-film-id="34708"><td>
					<span class="title">Rich Homie Quan - If You Ever Think I Will Stop Going In Ask RR</span>
					<a href="javascript:void(0)" class="pull-right remove"><i class="icon-remove"></i></a>
				</td></tr>

                <tr class="film" data-film-id="59">
                    <td>
                        <span class="title">Lil Wayne - Dedication 2 (Gangsta Grillz)</span>
                        <a href="javascript:void(0)" class="pull-right remove"><i class="icon-remove"></i></a>
                    </td>
                </tr>

				<tr class="selector">
					<td>
						<input type="text" class="selectfilm input-xlarge" placeholder="Type first letters" style="margin-bottom:0px;"/>
					</td>
				</tr>
			</table>

			<a href="javascript:void(0)" class="recommend btn btn-large btn-info">Get recommendations</a>
			<span class="recommendLoading" style="display:none;font-size:110%;padding-left:10px;"></span>
		</div>
	</div>	


<div id="recommendResultDialog" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Recommended Films</h3>
  </div>
  <div class="modal-body">
	Recommendations made by <a href="http://certifiedmixtapez.com" target="_blank">Certified Mixtapez</a> dataset (10,000+ ratings):
	<table class="table recommendedFilms">
		
	</table>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Done</a>
  </div>  	
</div>

<script type="text/javascript">
	$(function () {

		// removal
		$('.selectedfilms').on( "click", ".film .remove", function () {
			$(this).parents('tr:first').remove();
		});

	    // load films data
		$.ajax({
			type: "GET",async: true,dataType: "text",
			url: '@(VirtualPathUtility.ToAbsolute("~/js/albums-users.js"))',
		    success: function (data) {
		        window.moviesData = eval(data);
				window.movieIdToData = {};
				window.movieTitleToData = {};
				var movieTitles = [];
				for (var i = 0; i < window.moviesData.length; i++) {
				    var movieData = window.moviesData[i];
					movieIdToData[movieData.id.toString()] = movieData;
					movieTitleToData[movieData.title] = movieData;
					movieTitles.push(movieData.title);
				}

				$('.selectfilm').typeahead({ source: movieTitles } );
				$('.selectfilm').change(function () {
					var val = $.trim( $(this).val() );
					if (movieTitleToData[val]) {
						var movieData = movieTitleToData[val];
						var $tr = $('<tr class="film"><td><span class="title"></span><a href="javascript:void(0)" class="pull-right remove"><i class="icon-remove"></i></a></td></tr>');
						$tr.attr('data-film-id', movieData.id)
						var $title = $tr.find('.title');
						$title.text(movieData.title);

						$tr.insertBefore( $('.selectedfilms tr.selector') );
						$(this).val('');
					}
				});
			}
		});

		$('a.recommend').click(function () {

			var $btn = $(this);
			if ($btn.attr('disabled')=='disabled') return;
			$btn.attr('disabled', 'disabled');
			$('.recommendLoading').html('Loading 10,000 MovieLens ratings...').show('slow');

			setTimeout(function () {
				if ($('.recommendLoading').is(':visible'))
					$('.recommendLoading').hide('fast').html('<small>Wait please: cold start may take some time...</small>').show('fast');
			}, 5000);

			var selectedFilmIds = [];
			$(".selectedfilms tr.film").each(function () {
				selectedFilmIds.push( parseInt( $(this).attr('data-film-id') ) );
			});

			$.ajax({
				type: "POST", async: true, url: '@Url.Action("Recommend","Recommender")',
				data: {
					filmIdsJson: JSON.stringify(selectedFilmIds)
				},
				dataType: "json",
				success: function (res) {
					$btn.attr('disabled', null);
					$('.recommendLoading').hide();

					var $tbl = $('table.recommendedFilms');
					$tbl.find('tr').remove();
					$.each(res, function () {
						var filmIdStr = this.id.toString();
						var movieData = window.movieIdToData[filmIdStr];
						if (movieData) {
							var $tr = $('<tr><td class="title"><a target="_blank"/></td><td class="labels"></td></tr>');
							var $a = $tr.find('td.title a');
							$a.text(movieData.title);
							$a.attr('href', "http://certifiedmixtapez.com/Main/Details?refId=" + movieData.refId);
							$tbl.append($tr);
						}
					});
					$('#recommendResultDialog').modal();
				}
			});


		});



	});
</script>
	

NReco.Recommender/src/NReco.Recommender.Examples.MovieLensMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>NReco.Recommender for .NET Demo</title>
        
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>

		<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
		<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
		<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>

    </head>
    <body>	

		<div class="container">
			@RenderBody()
			<hr/>
		</div>

        @RenderSection("scripts", required: false)
    </body>
</html>